### ISSUE TITLE
Failed to activate the autocomplete-atom-api package

### ISSUE THREAD

**Issue by Maxskaz** [atom/autocomplete-atom-api#31] opened 2017-07-09 23:21 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [autocomplete-atom-api](https://github.com/atom/autocomplete-atom-api) package 0.10.1

### Stack Trace

Failed to activate the autocomplete-atom-api package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at requireAutocompleteManagerAsync (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/main.js:110:29)
    at Object.requireAutocompleteManagerAsync (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/main.js:31:15)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/main.js:107:16)
    at Object.consumeProvider_2_0 (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/main.js:86:23)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:256:22)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:377:25
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:386:18)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
  4x -9:34.9.0 core:backspace (input.hidden-input)
     -8:52 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:49.8.0 application:open-file (button.btn.btn-primary)
     -7:29.6.0 core:paste (div.line.cursor-line)
     -7:19.8.0 core:undo (span.syntax--text.syntax--plain.syntax--null-grammar)
     -7:12.7.0 core:save (input.hidden-input)
     -7:02.7.0 core:backspace (input.hidden-input)
     -6:58.8.0 editor:newline (input.hidden-input)
 10x -6:57.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
browser-plus 0.0.97 
```

**Comment by 50Wliu** [comment] 2017-07-10 04:50
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/autocomplete-plus/issues/851. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-07-10 04:50 UTC
